[test]
preload = ["./test/setup.ts"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["test/**", "dist/**"]
coverageReporter = ["text", "lcov"]
coverageThreshold = { lines = 0.9, functions = 0.9 }
